### ISSUE TITLE
Label Variable Traded

### ISSUE THREAD

**Issue by bluefish0125** [bradleyboyuyang/ML-HFT#2]
Hi I really appreciate the work your doing here! I am a bit confused on the way to decided to label buy and sell signals. So you said that if current bid is greater than the minimum ask for the next 15 minutes, it is a buy signal. However, I'm not sure why this is the case. If current bid is great than the minimum ask doesn't this suggest that the security has fallen in price?

**Comment by bradleyboyuyang** [comment]
If the current bid is less than the best ask for a quite amount of time, that means you can rarely profit from this trade itself (you need to cross a large spread for a buy order). 

If it is the opposite, one possibility is both bid and ask go down, in which case you don’t lose from the trade itself but will potentially lose when the price goes down further (but will also profit when price goes reversal). Yet another possibility is the bid ask spread becomes narrower, which indicates an increasing selling pressure that lowers down your cost of crossing the spread. This label does not necessarily mean a buy signal but predicting it accurately is beneficial for sure.

Overall, the project was done quite a long time ago and many details could be improved further. Feel free to explore more label choices on yourself.
